# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Cypress Run
        uses: react-redux-realworld-example-app
        with:
          build: npm install
          start : npm start
          wait-on: http://localhost:4100