
name: Test
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome 87
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2

      - name: Install Package
        run: npm install
      - name: Start Server
        run: nohup npm run start > /dev/null 2>&1 &
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true